name: packages

# Se secuta en cada push  
on:
  push:
    branches:
      - main
  pull_request:

# MV 
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest 
    steps:
    - name: Install dependencies...
      run: |
        sudo apt update && sudo apt install -y tar
# Permite compartir datos 
    - name: Clone repository
      uses: actions/checkout@v3 

    - name: Filling in home...
      run: echo $PWD 


    - name: Uploading... 
      uses: actions/upload-artifact@v3  
      with:
         name: i-haklab-home.tar.gz 
         path: i-haklab-home.tar.gz